kind: Service
apiVersion: v1
metadata:
  name: hd55-openapi-ui
spec:
  selector:
    pod: hd55-ambulance-webapi-label
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8081
