apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
images:
  - name: fiitkar/ambulance-ufe
    newName: fiitkar/ambulance-ufe
    newTag: 1.1.0 #aktuálna verzia docker obrazu, ktorú chcete aby používatelia - cvičiaci - videli nasadenú
  - name: fiitkar/ambulance-wl-webapi
    newName: fiitkar/ambulance-wl-webapi
    newTag: v1.0.1
