apiVersion: polyfea.github.io/v1alpha1
kind: WebComponent
metadata:
  name: hd55-ambulance-ufe-content
spec:
  microFrontend: hd55-ambulance-ufe
  element: hd55-ambulance-wl-app
  attributes:
    - name: base-path
      value: /hd55-ambulance-wl/
    - name: api-base
      value: /hd55-api
    - name: ambulance-id
      value: bobulova
  displayRules:
    - allOf:
        - context-name: main-content
        - path: "^(\\.?/)?hd55-ambulance-wl(/.*)?$"
