apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
images:
  - name: fiitkar/ambulance-ufe
    newName: fiitkar/ambulance-ufe # {"$imagepolicy":  "wac-hospital:ambulance-ufe:name"}
    newTag: main.20260316.1140 # {"$imagepolicy": "wac-hospital:ambulance-ufe:tag"}
  - name: fiitkar/ambulance-wl-webapi
    newName: fiitkar/ambulance-wl-webapi # {"$imagepolicy":  "wac-hospital:ambulance-webapi:name"}
    newTag: main.20260427.0931 # {"$imagepolicy": "wac-hospital:ambulance-webapi:tag"}
